### ISSUE TITLE
BUG (maybe) - Error loading and verifying case

### ISSUE THREAD

**Issue by blthayer** [FSEC-Photovoltaics/pvrpm-lcoe#36]
# Overview
When attempting to run `pvrpm`, I get the following error:
```bash
$ pvrpm run --case ./ ./richland.yaml
2022-02-05 11:22:12,974--ERROR: Error loading and verifying case: Couldn't find module for file richland.json!
```

# System/Environment
- OS: Ubuntu 20.04.3
- Python: 3.10.2
- SAM: 2021.12.02
- pvrpm installed from master at c6cd62a8de6576ff16e2d7355534f9ab216ac7eb

# Reproducing

Unzip [richland.zip](https://github.com/FSEC-Photovoltaics/pvrpm-lcoe/files/8008738/richland.zip) into a directory. It contains:
- richland.sam
- richland.json (exported data from SAM via "Generate Code" -> "JSON for inputs")
- richland.yaml (pvrpm configuration file)

From within the directory with the files above, execute `pvrpm run --case ./ ./richland.yaml`

# Misc Notes

The PVRPM docs seem to indicate that SAM should generate multiple JSON files, but this is not the case for me.

Also, when I use SAM to export to `json`, SAM crashes, but does successfully generate a single `json` file as well as the `.h` and `.so` files. Here's the output from SAM in my terminal:

```bash
...

(sam.bin:11945): Gtk-CRITICAL **: 11:17:53.945: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(sam.bin:11945): Gtk-CRITICAL **: 11:17:53.951: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(sam.bin:11945): Gtk-CRITICAL **: 11:17:53.956: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(sam.bin:11945): Gtk-CRITICAL **: 11:17:53.957: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
free(): double free detected in tcache 2
Aborted (core dumped)

```

**Comment by brandons209** [comment]
It looks like you are using a PVWatts model. PyPVRPM only supports Detailed PV Models. If you switch your model to that it should resolve this issue.

**Comment by blthayer** [comment]
Oops, I missed that note in the documentation on my first read through! Thanks for setting me straight.

**Comment by blthayer** [comment]
I'm still getting the same error after updating to use Detailed PV Models and a financial model that supports lifetime costs (as far as I could tell). I've attached a .zip archive with the exported `json` file and `yaml` configuration file
[richland_detailed.zip](https://github.com/FSEC-Photovoltaics/pvrpm-lcoe/files/8054236/richland_detailed.zip).

At any rate, I would consider updating the error message to give the user actionable information.

Looking at [the code](https://github.com/FSEC-Photovoltaics/pvrpm-lcoe/blob/2e8ebc716ca176e304a5f029a2facb792dc68fa3/pvrpm/core/case.py#L87) where I believe the error message originates from, it seems that the module name is being inferred from the name of the `json` file. However, as I mentioned in https://github.com/FSEC-Photovoltaics/pvrpm-lcoe/issues/39, SAM is only exporting a single `json` file for me (and I'm not sure if this is expected behavior or a problem with SAM. As mentioned above SAM does crash after creating the single `json` file plus the `.h` and `.so` files)

**Comment by brandons209** [comment]
I will take a look, this is most likely an error in SAM, there should be more then 1 file.

**Comment by brandons209** [comment]
I need you to send me your SAM case file to check it.

**Comment by brandons209** [comment]
Okay, I figured it out. I misread your initial bug report, you are selecting the wrong option when you click the "Generate Code" menu item. You need to do "Generate Code" -> "PySAM JSON" not "JSON for Inputs".

**Comment by brandons209** [comment]
As an addition to this, I realize the `Getting Started` page did say select `JSON for Inputs`, I think this changed with the latest version of SAM. Sorry for the confusion as I didn't realize this, I will fix the docs now.

**Comment by blthayer** [comment]
I'm now able to get my case past this error thanks to the updated documentation.
